version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog_cms
    ports:
      - "82:80"
    volumes:
      - ../blog:/var/www/html
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: blog_cms_db
    environment:
      MYSQL_ROOT_PASSWORD: kraxx181818
    networks:
      - mynetwork
    volumes:
      - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: blog_cms_phpmyadmin
    links:
      - db
    ports:
      - "8082:80"
    networks:
      - mynetwork
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: kraxx181818
networks:
  mynetwork:

volumes:
  mysql_data: